using StudyTaskManager.Application.Abstractions.Messaging;

namespace StudyTaskManager.Application.Entity.GroupChatParticipantLastReads.Queries.GroupChatParticipantLastReadGet;
public sealed record GroupChatParticipantLastReadGetQuery(Guid UserId, Guid GroupChatId) : IQuery<GroupChatParticipantLastReadResponse>;